name: Check shell and Lua
on: [ push ]
jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check Lua files
      uses: nebularg/actions-luacheck@v1
      with:
        files: ./nvim
    - name: fish-shop/syntax-check
      uses: fish-shop/syntax-check@v1.5.0


